// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBooking.DAL.Entities;

#nullable disable

namespace TicketBooking.DAL.Migrations
{
    [DbContext(typeof(TicketBookingDBContext))]
    [Migration("20260212193039_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBooking.DAL.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("NetFare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Booking", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(500),
                            CreatedAt = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(502),
                            DiscountPercent = 0m,
                            NetFare = 2400m,
                            Status = "Confirmed",
                            TotalFare = 2400m,
                            UserId = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(504),
                            CreatedAt = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(505),
                            DiscountPercent = 0m,
                            NetFare = 1200m,
                            Status = "Pending",
                            TotalFare = 1200m,
                            UserId = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(506),
                            CreatedAt = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(507),
                            DiscountPercent = 10m,
                            NetFare = 1980m,
                            Status = "Confirmed",
                            TotalFare = 2200m,
                            UserId = 3,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookingDate = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(509),
                            CreatedAt = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(509),
                            DiscountPercent = 0m,
                            NetFare = 1100m,
                            Status = "Cancelled",
                            TotalFare = 1100m,
                            UserId = 4,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.BookingSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("BookingId", "SeatId")
                        .IsUnique();

                    b.ToTable("BookingSeat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 1,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 2,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 3,
                            SeatId = 5
                        });
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GreenLine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shohagh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hanif"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Soudia"
                        });
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2400m,
                            BookingId = 1,
                            Method = "Card",
                            PaymentDate = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(542),
                            Status = "Paid",
                            TransactionId = "TXN1001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1200m,
                            BookingId = 2,
                            Method = "Cash",
                            PaymentDate = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(547),
                            Status = "Failed",
                            TransactionId = "TXN1002"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1980m,
                            BookingId = 3,
                            Method = "Mobile Banking",
                            PaymentDate = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(549),
                            Status = "Paid",
                            TransactionId = "TXN1003"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1100m,
                            BookingId = 4,
                            Method = "Card",
                            PaymentDate = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(550),
                            Status = "Refunded",
                            TransactionId = "TXN1004"
                        });
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Route", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "Chittagong",
                            Origin = "Dhaka"
                        },
                        new
                        {
                            Id = 2,
                            Destination = "Sylhet",
                            Origin = "Dhaka"
                        },
                        new
                        {
                            Id = 3,
                            Destination = "Rajshahi",
                            Origin = "Dhaka"
                        },
                        new
                        {
                            Id = 4,
                            Destination = "Sylhet",
                            Origin = "Chittagong"
                        });
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Seat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBooked = false,
                            SeatNumber = "A1",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsBooked = false,
                            SeatNumber = "A2",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsBooked = false,
                            SeatNumber = "A3",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsBooked = false,
                            SeatNumber = "A4",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsBooked = false,
                            SeatNumber = "B1",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsBooked = false,
                            SeatNumber = "B2",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsBooked = false,
                            SeatNumber = "B3",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 8,
                            IsBooked = false,
                            SeatNumber = "B4",
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(477),
                            Email = "rahim@gmail.com",
                            FullName = "Rahim",
                            Password = "Rahim@123",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(479),
                            Email = "karim@gmail.com",
                            FullName = "Karim",
                            Password = "Karim@123",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(480),
                            Email = "salma@gmail.com",
                            FullName = "Salma",
                            Password = "Salma@123",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 12, 19, 30, 39, 357, DateTimeKind.Utc).AddTicks(482),
                            Email = "rita@gmail.com",
                            FullName = "Rita",
                            Password = "Rita@123",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RouteId");

                    b.ToTable("Vehicle", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseFare = 1200m,
                            CompanyId = 1,
                            DepartureTime = new DateTime(2026, 2, 13, 10, 0, 0, 0, DateTimeKind.Local),
                            RouteId = 1,
                            TotalSeats = 40,
                            Type = "Bus"
                        },
                        new
                        {
                            Id = 2,
                            BaseFare = 1100m,
                            CompanyId = 2,
                            DepartureTime = new DateTime(2026, 2, 13, 14, 0, 0, 0, DateTimeKind.Local),
                            RouteId = 2,
                            TotalSeats = 40,
                            Type = "Bus"
                        },
                        new
                        {
                            Id = 3,
                            BaseFare = 1000m,
                            CompanyId = 3,
                            DepartureTime = new DateTime(2026, 2, 13, 16, 0, 0, 0, DateTimeKind.Local),
                            RouteId = 3,
                            TotalSeats = 40,
                            Type = "Bus"
                        },
                        new
                        {
                            Id = 4,
                            BaseFare = 1300m,
                            CompanyId = 4,
                            DepartureTime = new DateTime(2026, 2, 13, 18, 0, 0, 0, DateTimeKind.Local),
                            RouteId = 4,
                            TotalSeats = 40,
                            Type = "Bus"
                        });
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Booking", b =>
                {
                    b.HasOne("TicketBooking.DAL.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketBooking.DAL.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.BookingSeat", b =>
                {
                    b.HasOne("TicketBooking.DAL.Entities.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketBooking.DAL.Entities.Seat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Payment", b =>
                {
                    b.HasOne("TicketBooking.DAL.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("TicketBooking.DAL.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("TicketBooking.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Seat", b =>
                {
                    b.HasOne("TicketBooking.DAL.Entities.Vehicle", "Vehicle")
                        .WithMany("Seats")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Vehicle", b =>
                {
                    b.HasOne("TicketBooking.DAL.Entities.Company", "Company")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketBooking.DAL.Entities.Route", "Route")
                        .WithMany("Vehicles")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Booking", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Company", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Route", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Seat", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TicketBooking.DAL.Entities.Vehicle", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
